export const RULE_LIBRARY = [
  {
    id: "lantern_ward",
    name: "Lantern Ward",
    icon: "🕯️",
    duration: 6,
    delayOptions: [1, 2, 3],
    description: "Your least-advanced knight or bishop gains a ward and cannot be captured while the rule lasts.",
  },
  {
    id: "mason_pause",
    name: "Mason Pause",
    icon: "🧱",
    duration: 6,
    delayOptions: [1, 2],
    description: "The enemy's most-advanced pawn is rooted for its next two turns.",
  },
  {
    id: "quiet_grain",
    name: "Quiet Grain",
    icon: "🌾",
    duration: 5,
    delayOptions: [1, 2, 3],
    description: "Your most-advanced pawn becomes untouchable, but it also cannot capture.",
  },
  {
    id: "stewards_seal",
    name: "Steward's Seal",
    icon: "🔖",
    duration: 6,
    delayOptions: [2, 3],
    description: "Your rook nearest the king gains a ward. Whenever it moves, its origin becomes a spring square.",
  },
  {
    id: "velvet_tax",
    name: "Velvet Tax",
    icon: "🎭",
    duration: 4,
    delayOptions: [1, 2],
    description: "The enemy's highest-value mobile piece cannot capture.",
  },
  {
    id: "marble_annex",
    name: "Marble Annex",
    icon: "🏛️",
    duration: 6,
    delayOptions: [1, 2, 3],
    description: "d3, e3, d6, and e6 become sanctuary squares. Captures onto them are forbidden.",
  },
  {
    id: "rosewell",
    name: "Rosewell",
    icon: "🌹",
    duration: 6,
    delayOptions: [1, 2, 3],
    description: "c4, f4, c5, and f5 become spring squares. Entering them grants a brief ward.",
  },
  {
    id: "cinder_walk",
    name: "Cinder Walk",
    icon: "🔥",
    duration: 6,
    delayOptions: [1, 2, 3],
    description: "b4, g4, b5, and g5 become cinder squares. Entering them removes your next capture.",
  },
  {
    id: "quiet_cloister",
    name: "Quiet Cloister",
    icon: "🤫",
    duration: 6,
    delayOptions: [1, 2],
    description: "c3, f3, c6, and f6 become hush squares. Long-range pieces cannot capture onto them.",
  },
  {
    id: "ivy_stair",
    name: "Ivy Stair",
    icon: "🌿",
    duration: 6,
    delayOptions: [2, 3],
    description: "a4, a5, h4, and h5 become ivy squares. Entering one roots that piece for its next turn.",
  },
  {
    id: "kings_gallery",
    name: "King's Gallery",
    icon: "👑",
    duration: 5,
    delayOptions: [1, 2, 3],
    description: "Squares around your king become sanctuary squares while the rule lasts.",
  },
  {
    id: "border_edict",
    name: "Border Edict",
    icon: "🧭",
    duration: 6,
    delayOptions: [1, 2],
    description: "Your knights and bishops may not end moves on edge squares.",
  },
  {
    id: "hearth_right",
    name: "Hearth Right",
    icon: "🪵",
    duration: 8,
    delayOptions: [2, 3],
    description: "Any piece that captures gains a brief ward.",
  },
  {
    id: "echo_discipline",
    name: "Echo Discipline",
    icon: "🪞",
    duration: 8,
    delayOptions: [1, 2],
    description: "If a player moves the same piece on consecutive turns, that piece cannot capture on its next move.",
  },
  {
    id: "center_grace",
    name: "Center Grace",
    icon: "✨",
    duration: 7,
    delayOptions: [1, 2, 3],
    description: "Pieces ending on d4, e4, d5, or e5 gain a brief ward.",
  },
  {
    id: "frost_ledger",
    name: "Frost Ledger",
    icon: "❄️",
    duration: 7,
    delayOptions: [1, 2, 3],
    description: "Pieces leaving the central four squares cannot capture on their next move.",
  },
  {
    id: "rooks_ribbon",
    name: "Rook's Ribbon",
    icon: "🎀",
    duration: 5,
    delayOptions: [2, 3],
    description: "Every rook move leaves a spring square on its origin.",
  },
  {
    id: "bishops_ash",
    name: "Bishop's Ash",
    icon: "🪶",
    duration: 5,
    delayOptions: [2, 3],
    description: "Every bishop move leaves a cinder square on its origin.",
  },
  {
    id: "knights_halo",
    name: "Knight's Halo",
    icon: "🌙",
    duration: 6,
    delayOptions: [1, 2],
    description: "A knight ending on a light square gains a brief ward.",
  },
  {
    id: "dark_choir",
    name: "Dark Choir",
    icon: "⛪",
    duration: 6,
    delayOptions: [1, 2],
    description: "A bishop ending on a dark square gains a brief ward.",
  },
  {
    id: "pawn_toll",
    name: "Pawn Toll",
    icon: "⏳",
    duration: 8,
    delayOptions: [1, 2, 3],
    description: "A pawn that advances two squares cannot capture on its next move.",
  },
  {
    id: "court_respite",
    name: "Court Respite",
    icon: "🫧",
    duration: 6,
    delayOptions: [1, 2, 3],
    description: "Queens cannot capture pieces standing on sanctuary or spring squares.",
  },
  {
    id: "sentinel_arc",
    name: "Sentinel Arc",
    icon: "🛡️",
    duration: 5,
    delayOptions: [2, 3],
    description: "Orthogonally adjacent squares to your king become spring squares.",
  },
  {
    id: "silent_file",
    name: "Silent File",
    icon: "📜",
    duration: 6,
    delayOptions: [1, 2],
    description: "Your king's file becomes hush squares while the rule lasts.",
  },
  {
    id: "pilgrim_step",
    name: "Pilgrim Step",
    icon: "🚪",
    duration: 7,
    delayOptions: [1, 2, 3],
    description: "b2, g2, b7, and g7 become spring squares.",
  },
  {
    id: "harbor_law",
    name: "Harbor Law",
    icon: "⚓",
    duration: 6,
    delayOptions: [1, 2, 3],
    description: "Captures on the a-file and h-file are forbidden.",
  },
  {
    id: "crown_drift",
    name: "Crown Drift",
    icon: "🌊",
    duration: 6,
    delayOptions: [2, 3],
    description: "After every move, the moved piece is rooted until its owner's next turn.",
  },
  {
    id: "far_travelers",
    name: "Far Travelers",
    icon: "🧳",
    duration: 6,
    delayOptions: [1, 2],
    description: "Knights and bishops that enter the enemy half gain a brief ward.",
  },
  {
    id: "mirror_tithe",
    name: "Mirror Tithe",
    icon: "💠",
    duration: 7,
    delayOptions: [1, 2, 3],
    description: "A piece that captures from a dark square is rooted until its owner's next turn.",
  },
  {
    id: "reed_vow",
    name: "Reed Vow",
    icon: "🎐",
    duration: 6,
    delayOptions: [1, 2],
    description: "Your queen cannot capture, but it gains a ward while the rule lasts.",
  },
  {
    id: "volatile_crest",
    ruleSet: "chaos",
    name: "Volatile Crest",
    icon: "💥",
    duration: 5,
    delayOptions: [1, 2],
    description: "A marked minor piece erupts on capture. Any adjacent non-king pieces are shocked when it captures or is captured.",
  },
  {
    id: "static_clasp",
    ruleSet: "chaos",
    name: "Static Clasp",
    icon: "⚡",
    duration: 5,
    delayOptions: [1, 2],
    description: "Your marked knight or bishop discharges on contact. Ending orthogonally beside an enemy shocks that enemy.",
  },
  {
    id: "riposte_shroud",
    ruleSet: "chaos",
    name: "Riposte Shroud",
    icon: "🗡️",
    duration: 6,
    delayOptions: [1, 2],
    description: "Your rook nearest the king gains riposte. If it is captured, the capturer is shocked and loses its next capture.",
  },
  {
    id: "thunder_cells",
    ruleSet: "chaos",
    name: "Thunder Cells",
    icon: "⛈️",
    duration: 6,
    delayOptions: [1, 2],
    description: "d4, e4, d5, and e5 become shock tiles. Entering one roots the piece and removes its next capture.",
  },
  {
    id: "ember_wake",
    ruleSet: "chaos",
    name: "Ember Wake",
    icon: "♨️",
    duration: 6,
    delayOptions: [1, 2],
    description: "Every move leaves a brief ember on its origin. The next piece entering that square is shocked.",
  },
  {
    id: "surge_file",
    ruleSet: "chaos",
    name: "Surge File",
    icon: "🌩️",
    duration: 5,
    delayOptions: [1, 2],
    description: "One central file turns live. Every square on that file becomes a shock tile while the rule lasts.",
  },
  {
    id: "chain_static",
    ruleSet: "chaos",
    name: "Chain Static",
    icon: "🔗",
    duration: 6,
    delayOptions: [1, 2],
    description: "Whenever one of your pieces ends orthogonally adjacent to an enemy, that enemy is shocked.",
  },
  {
    id: "aftershock_tithe",
    ruleSet: "chaos",
    name: "Aftershock Tithe",
    icon: "🫨",
    duration: 6,
    delayOptions: [1, 2],
    description: "Every capture shocks the capturer and one adjacent allied piece.",
  },
  {
    id: "storm_collar",
    ruleSet: "chaos",
    name: "Storm Collar",
    icon: "🌪️",
    duration: 6,
    delayOptions: [1, 2],
    description: "The enemy's highest-value mobile piece is stormbound. Whenever it moves, it is rooted for its next turn.",
  },
  {
    id: "tempest_ring",
    ruleSet: "chaos",
    name: "Tempest Ring",
    icon: "🌀",
    duration: 6,
    delayOptions: [1, 2],
    description: "Squares around your king crackle with static. Enemy pieces entering them are shocked.",
  },
];

export const RULE_BY_ID = Object.fromEntries(
  RULE_LIBRARY.map((rule) => [rule.id, rule]),
);
